### ISSUE TITLE
Запуск нового ICO 

### ISSUE THREAD

**Issue by soundbit** [ethereumclassic/README#12]
Предлагаю на официальном сайте разместить обращение к хакеру, чтобы он перевёл часть своих токенов для запуска нового ICO, и всё-таки кто-то должен выйти из тени и сформировать новую команду

**Comment by whatisgravity** [comment]
Can anyone provide a translation? I would like to assist but unfortunately I lack the ability to read it.

**Comment by arvicco** [comment]
@whatisgravity Don't worry, it's not dev related.

**Comment by arvicco** [comment]
Translation @soundbit :
"I suggest on the official website to place an appeal to the hacker, so he moved some of their tokens to launch a new ICO, and yet someone has to come out of the shadows and form a new team"

**Comment by arvicco** [comment]
We are not interested in cooperation with theDAO attacker. Let him mind his business, we will mind ours. If someone feels like supporting our project, our donation addresses listed here: 

https://www.reddit.com/r/EthereumClassic/comments/4u4o61/call_for_action_what_can_i_do_to_help_ethereum/

-----
Зачем нам это? Мы занимаемся своим делом и не лезем в чужие. Если кто-то хочет нас поддержать, адреса для пожертвований по линку выше.

**Comment by whatisgravity** [comment]
I agree, anyone is welcome to anonymous donate, if the sum becomes large enough we can use a contract to act as a trust for a decentralized foundation but no one should be negotiating anything.

**Comment by ProphetDaniel** [comment]
Right now Ethereum Classic got a lot of attention due to the press and recent increase in market capitalization. As time goes by with the right decisions we might see Ethereum Classic to become mature and trusted by the community. Immutability was preserved at Ethereum classic, hackers are motivated to discover system vulnerabilities with deserved bounties. The history of the public ledger cannot be rewritten. Moral principles are not left aside for rescuing one or another company. I mean We have plenty of values to share with the community.

**Comment by arvicco** [comment]
So far, a small donation from DAO attacker proved to be more of a headache than a help.
