### ISSUE TITLE
Professionalizing Ethereum Classic to provide Smart Contracts System of the Future

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumclassic/README#24]
Now that Ethereum Classic has got the community's attention. Better planning the professionalization of the organization is required. First questions are: do we need a foundation, crowd funding, consultancy, how to attract best in class experts, how to behave upon forked Ethereum technological advances and so on.

**Comment by bart-w0** [comment]
These are lot of questions in one post. I think what we need first is a _framework_, a way how we will make such decisions. I doubt a github issue is a way to do it. I think the community would like us to be open and decentralised and take part in shaping ETC. How this is going to be achieved - I don't know yet. I rely on our coordinator in that respect. But I do think we should create that framework (personally I see a forum as a good starting point).

**Comment by matthewjamesr** [comment]
I and many other developers agree that transparency is going to be a massive first-issue. Already there are fears on reddit about developers taking over and changing the platform, etc.

We can either create a dAPP for ETCIPs, a basic web app to browse and submit ETCIPs, etc. We could then at a minimal make it show developer's votes with a requirement to state why they voted that way.

Thoughts @whatisgravity? I fear if we do not head off these rumblings with a solid, fully transparent process, we will struggle greatly.

**Comment by whatisgravity** [comment]
We do currently have a repository for EIPS, which should probably be upgraded to be ECIPs. I'm open to anyone making those changes. I'm also for creating an easy to use platform to encourage more improvement feedback from the wider community. I think it is worthwhile that people who are not developers have their voices heard, so everyone can have more stake in the project. It may be worthwhile to create a standardized platform for this over trying to make reddit fit this purpose.

We may need to accept certain level of grumbling, I don't think grumbling will ever go away because there is too much at stake and we are in a rare situation where people have financial motivation to troll from both sides of the fork.

I think our best response is to remain proactive regarding this topic. Work hard to ensure the community is open to anyone interested in volunteering, make it easy to volunteer so people who invest their time are able to maximize their contributions, and in my opinion most importantly remain merit based so skilled volunteers get as much say as people who joined before they did and transparent as possible. 

I have stated I'm against the idea of crowd sales, I'm even hesitant to take donations until we have a decentralized multisig trust framework we can control held funds in a transparent way. To me this structure seems to be more important by the day and if it is not started by someone else I can begin work on it once I finish my tasks relating to geth/mist.
