### ISSUE TITLE
Linkedin company page missing for attracting skilled personnel

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumclassic/README#27]
Great development communities have a way to enlist best developers as possible for making marvellous innovations to come true, positively surprising the motivating community. The result is reflected in the overal network outcome.

As there's no Ethereum Classic Linkedin page it could be so that we are missing great people who doesn't even know we exist. My suggestion is to create a company page at Linkedin.

**Comment by arvicco** [comment]
@ProphetDaniel 

Care to take the initiative? We are a decentralized community. If anyone feels strongly that something needs to be done, and no one is doing it, no need to ask for permissions. Just announce your initiative as an issue here, announce the plan and list resources needed, initiate discussion. Correct the plan as per discussion outcome. If there the issue is non-contentious and no serious objections raised, just go ahead and do it. You are in charge unless it was decided otherwise while discussing the issue. Then just go ahead and implement the plan.

**Comment by ProphetDaniel** [comment]
@arvicco I need to send a private message in this regard. Email me please.

**Comment by ProphetDaniel** [comment]
I've opened the LinkedIn company page successfully more details enter LinkedIn and look for Ethereum Classic.
