### ISSUE TITLE
How should pools run the client?

### ISSUE THREAD

**Issue by etherninja** [ethereumclassic/README#4]
I have a pool. It is running --oppose-dao-fork or should I compile the source from the repo?

http://ethc.epool.io

**Comment by arvicco** [comment]
Great! Could you make a post about your pool in https://www.reddit.com/r/EthereumClassic/, so that miners who disagree with pro-HF stance of major pools know where to point their hashrate? Thanks a lot!

Regarding your question, yes, running official client with --oppose-dao-fork will perfectly do for now.

**Comment by whatisgravity** [comment]
I'm working on a clean client without the changes and that will build easily as we speak it should be ready within the hour. I will have it ready at github.com/ethereumproject/go-ethereum

**Comment by whatisgravity** [comment]
In the meantime you should run the etherfork client with the --oppose-dao flag enabled. Soon we will have an alternative client and mist client that will not require any special flags. 

It is truly unfair they did not release two separate clients. They clearly do not want to give real choices, because they are not bad developers and good developers know better. Requiring a CLI flag is "tyranny of the default".

**Comment by etherninja** [comment]
ok. i will update the client when it comes available. for all practical purposes, the client deployed should work for now. i you want to post it, that is fine.

**Comment by arvicco** [comment]
Doesn't seem like your stratum us.ethc.epool.io:8008 is running. Or your stats are calculated wrong. I'm pointing some hash to it, but it is not showing in stats.

**Comment by whatisgravity** [comment]
The client is available, please let me know if you have issues.

**Comment by arvicco** [comment]
I don't see any problems with Ethereum Classic as a descriptive moniker to differentiate from forked ETH that claims Ethereum name. This is up to community that will form around the project though, I don't intend to play Vitalik and impose my views. Anyways, it's a topic for other issue.

**Comment by arvicco** [comment]
@etherninja Sorry, I had my settings mixed up. Stratum is working, let's bring more miners there.

**Comment by arvicco** [comment]
Is it possible to persuade you to lower the pool fee to 0.9% or lower initially, to encourage adoption? We can work out something compensate your efforts. If you want to chat, Skype: arvicco. Thanks!

**Comment by arvicco** [comment]
@etherninja Is it possible to persuade you to lower the pool fee to 0.9% or lower initially, to encourage adoption? We can work out something compensate your efforts. If you want to chat, Skype: arvicco. Thanks!

**Comment by whatisgravity** [comment]
Just pushed a fix for the issue with make. If you have any other issues, I would be happy to help troubleshoot.

**Comment by arvicco** [comment]
Slack: #mining, #poolops channels
