### ISSUE TITLE
ETHC block explorer?

### ISSUE THREAD

**Issue by arvicco** [ethereumclassic/README#7]
Is anyone up to creating Ethereum Classic block explorer? Something like https://etherscan.io/, or maybe something much simpler. There should be an easy way for people to check on ETHC chain post-fork and see for themselves that it is still alive and kicking.

**Comment by whatisgravity** [comment]
It is very unfortunate to see that none of the existing ones are open source. The Bitcoin community did a much better job of maintaining associated tools in the open with the help of the community. We will either have to reach out to the existing blockchain explorers to open their source or begin building our own.

**Comment by whatisgravity** [comment]
http://classic.aakilfernandes.com/#/

https://github.com/aakilfernandes/explorer

It is very rudimentary but it is a good leaping off point for starting a solid open source explorer.

**Comment by arvicco** [comment]
Will link on http://explorer.ethereumclassic.com shortly.

**Comment by whatisgravity** [comment]
We have three now: http://gastracker.io/

All have very basic features though, they need a lot of work.

**Comment by arvicco** [comment]
Yes, I added it to Reddit sticky.

**Comment by matthewjamesr** [comment]
Can we fork any of these trackers to this namespace? If so I will contrib/maintain features in-step with developments/requests.

Or if we want to create custom that is fine as well.

**Comment by whatisgravity** [comment]
You are welcome to fork the existing ones or a custom one. I believe a diversity of block chain explorer foundations is good as long as we can avoid the organization being field with several partially started projects.

**Comment by classic1999** [comment]
etcchain.com - A new Ethereum classic block Explorer launches,include etc block Explorer;etc and eth price; miner index; address QR code。

**Comment by etherx-dev** [comment]
http://etherx.com is being worked on, try it out.

**Comment by arvicco** [comment]
Multiple block explorers functional:
http://gastracker.io/
https://etcchain.com/
http://etherx.com/
http://etherhub.io/

**Comment by MelbourneDeveloper** [comment]
@arvicco 

I have been using Gastracker in the past, but it actually gives incorrect results sometimes. For example, some addresses show no balance while other explorers show a balance for the same address. I can prove this because http://etherhub.io shows a balance for an address where Gastracker doesn't.

Etcchain is currently down and has often been flaky.

http://etherhub.io/ looks like a good block explorer but I can't get any information on the API. There seems to be no documentation.

What is this http://etherx.com/ website you speak of? 

As far as I am concerned there is no reliable blockchain explorer API for Ethereum classic. Do I need to open a new issue?

**Comment by MelbourneDeveloper** [comment]
@etherx-dev  , did you ever get your explorer working? 

The website just times out.
