### ISSUE TITLE
Change tx nonce to avoid replay attacks?

### ISSUE THREAD

**Issue by arvicco** [ethereumclassic/README#8]
As per discussion here: https://www.reddit.com/r/EthereumClassic/comments/4tgyzb/a_proposal_on_how_to_proceed/

The issue has both technical and social aspects. Replay attack risk is currently used as an instrument to scare people of using ETHC. Of course, the possibility to get rid of this problem completely and decisively looks very tempting...

@whatisgravity What do you think about it?

**Comment by ethernomad** [comment]
This is my initial attempt at implementing it: https://github.com/ethernomad/go-ethereum-classic/commit/9f58a737b27070df05ac6f31a3dc0ebd516a978f

**Comment by whatisgravity** [comment]
I believe I solved this issue by simply leveraging the BadHashes function found in core/blocks.go. I added the DAO HF hash, this limits our DAO code to a single line in an existing system to stop HF issues. 

I think we should not change our tx nonce because we want maximum compatibility with *all* older clients. If we make changes like this our client would not be retroactively compatible, and currently this is very important. 

We need to petition to the Ethereum Foundation that they do more to complete the split now that we clearly are capable of maintaining the original Ethereum network.

**Comment by arvicco** [comment]
"do more to complete the split" - what could they do, exactly? what specifically should we be lobbying for?

**Comment by whatisgravity** [comment]
In all fairness, before I make the suggestions, it would have been difficult for us if they did a clean break immediately because we did not yet have bootstrap nodes. We would have had everyone start the client with a list of peers shared via other mediums. As we get bootstrap nodes online something like this would be desirable long term. 

Since they already committed to doing a hard fork, requiring all users to upgrade, they could do something more dramatic than what they have done, I suspect they did not do this because they assumed we would want to join their chain.

**Option 1**
Change the handshake message from 0x00. This will cause each side of the split to reject each others messages immediately without any need to do further checks. This is desirable because it would limit potential attack surface and for them it is a simple change. It may look slightly less pretty in the code but so does the rest of the DAO hard fork.

https://github.com/ethereum/go-ethereum/blob/506c9277911746dfbab0a585aee736bd3095f206/p2p/peer.go#L44

This is my preferred option because it lets us both upgrade to ruleset's named "casper" without having issues and rejects the connection with the least number of checks.

**Option 2** 
*This is the suggestion that ethernomad is demonstrating above*

I would have assumed they would treat this fork as a ruleset change. Making the DAOFork functionally similar to homestead code, it already is in ways but it is missing key parts that would force the split the network. 

In the source code, a ruleset change is defined as:

// RuleSet is an interface that defines the current rule set during the
// execution of the EVM instructions (e.g. whether it's homestead)

Adding hard coded changes to overwrite the execution of specific contracts falls under "defines the current rule set during execution of the EVM instructions". To me it seems obvious this would qualify as a new ruleset. 

This change would require slightly more modifications than the above solution but still not many changes would be required to accomplish this. Also it would allow them to continue to support both sides of the fork utilizing the existing drop down for testnet,mainnet,etc

https://github.com/ethereum/go-ethereum/blob/master/core/vm/environment.go
...

**Comment by whatisgravity** [comment]
I would not recommend using the HFConditionalTransfer contract, it is based on a variable in the WhiteHatDAO that could change without announcement. It is a dangerous to use this contract. Seems like a hacky solution.

#How To

**Description**
The *RelaySafeSplit* Kraken contract is much better, it uses another contract as an oracle, the oracle was deployed and checked the range between a defined time period then locked the result so it can not be tampered with or changed.

The result to a publicly accessible variable and can not be altered. (Assuming they do not change the blockchain)

It allows you to solve the entirely resolve the issue in a single contract too.

**Instructions**
I recomend using the RelaySafeSplit() 

You can deploy the code yourself or just use contract found at 0x341e790174e3a4d35b65fdc067b6b5634a61caea it is not hard coded and can be used by anyone

1. Create 2 new accounts, 1 for the destination of your tokens on each side of the fork. It does not matter which client you use because the accounts/keys are valid on chain. 

2. Obtain the JSON ABI from http://etherscan.io/address/0x341e790174e3a4d35b65fdc067b6b5634a61caea#code

3. Load Ethereum Wallet, Select "Contracts", Scrolldown and Select "Watch Contract"

4. Put in the name, the address and paste in the JSON ABI 

5. Click the contract

6. Scroll down to "Write to contract", click the "Select Function" dropdown

7. Execute the function "split"

8. Paste in each of the 2 new addresses, specify the balance you want to split and send it. 

9. Now your coins are safely split and can be used from now on without any further need to worry about the issue.

**Comment by arvicco** [comment]
Further discussion: https://github.com/ethereumproject/ECIPs/issues/7
